pipeline{
   agent any
   tools{
    maven 'M2_HOME'
   } 
   stages{
    stage('sonar-scan'){
        steps{
        withSonarQubeEnv('sonarQube'){
        sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Romeo092_geo-app'
        }
           
        }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    // stage('quality-gate'){
    //     steps{
    //         timeout(time: 1, unit: 'HOURS'){
    //                 waitForQualityGate abortPipeline: true
    //             }
    //     }

    //     }

    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
                target/bio*.jar \
                   "http://ec2-34-239-248-247.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
    
        
        }
   
        }
    
    }
    
    }